### ISSUE TITLE
Can you please add a release to this repository?

### ISSUE THREAD

**Issue by Fbeen** [a2lix/AutoFormBundle#3]
Hi i like this bundle and use it for my own "fbeen/simplecmsbundle". But composer complains about the dev-master version. Would you launch the first release for me and update the bundle on Packagist?

Many thanks in advance

**Comment by webda2l** [comment]
Hi,

I just created https://github.com/a2lix/AutoFormBundle/tree/0.1-beta.1 that you can use

**Comment by Fbeen** [comment]
Thanks, i will try if it works :-)

Regards,

Frank

2016-11-07 14:13 GMT+01:00 David ALLIX <notifications@github.com>:
